// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation
import ArkanaKeysInterfaces

public enum ArkanaKeys {
    @inline(__always)
    fileprivate static let salt: [UInt8] = [
        0xcd, 0x42, 0xd7, 0x73, 0xde, 0x43, 0xe3, 0x19, 0x70, 0xc8, 0x93, 0x63, 0x1, 0xf1, 0x44, 0x72, 0x89, 0x2f, 0xc9, 0x98, 0xc1, 0xdc, 0xa8, 0x92, 0x6a, 0xea, 0xba, 0xb2, 0x4c, 0xaf, 0x86, 0xca, 0x7b, 0x18, 0x48, 0x57, 0xc, 0x1f, 0xff, 0xcf, 0x14, 0x79, 0x96, 0x5a, 0xda, 0x65, 0x26, 0xa1, 0x86, 0x96, 0x9, 0xed, 0xcf, 0x9a, 0xa0, 0xbe, 0xce, 0x54, 0xc5, 0x2d, 0x51, 0xc0, 0x8a, 0xe0
    ]

    static func decode(encoded: [UInt8], cipher: [UInt8]) -> String {
        return String(decoding: encoded.enumerated().map { offset, element in
            element ^ cipher[offset % cipher.count]
        }, as: UTF8.self)
    }

    static func decode(encoded: [UInt8], cipher: [UInt8]) -> Bool {
        let stringValue: String = Self.decode(encoded: encoded, cipher: cipher)
        return Bool(stringValue)!
    }

    static func decode(encoded: [UInt8], cipher: [UInt8]) -> Int {
        let stringValue: String = Self.decode(encoded: encoded, cipher: cipher)
        return Int(stringValue)!
    }
}

public extension ArkanaKeys {
    struct Global: ArkanaKeysGlobalProtocol {
        public init() {}

        @inline(__always)
        public let botAccessKey: String = {
            let encoded: [UInt8] = [
                0xaf, 0x2d, 0xa3, 0x2c, 0xbf, 0x20, 0x80, 0x7c, 0x3, 0xbb, 0xcc, 0x8, 0x64, 0x88
            ]
            return ArkanaKeys.decode(encoded: encoded, cipher: ArkanaKeys.salt)
        }()
    }
}

public extension ArkanaKeys {
    struct Release: ArkanaKeysEnvironmentProtocol {
        public init() {}

        @inline(__always)
        public let apiKey: String = {
            let encoded: [UInt8] = [
                0xa8, 0x3a, 0xb6, 0x1e, 0xae, 0x2f, 0x86, 0x46, 0x2, 0xad, 0xff, 0x6, 0x60, 0x82, 0x21, 0x2d, 0xe2, 0x4a, 0xb0
            ]
            return ArkanaKeys.decode(encoded: encoded, cipher: ArkanaKeys.salt)
        }()
    }
}

public extension ArkanaKeys {
    struct Debug: ArkanaKeysEnvironmentProtocol {
        public init() {}

        @inline(__always)
        public let apiKey: String = {
            let encoded: [UInt8] = [
                0xa8, 0x3a, 0xb6, 0x1e, 0xae, 0x2f, 0x86, 0x46, 0x14, 0xad, 0xf1, 0x16, 0x66, 0xae, 0x2f, 0x17, 0xf0
            ]
            return ArkanaKeys.decode(encoded: encoded, cipher: ArkanaKeys.salt)
        }()
    }
}
