// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

public protocol ArkanaKeysGlobalProtocol {
    var botAccessKey: String { get }
}

public protocol ArkanaKeysEnvironmentProtocol {
    var apiKey: String { get }
}
